/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class maxit_gui_GUI */

#ifndef _Included_maxit_gui_GUI
#define _Included_maxit_gui_GUI
#ifdef __cplusplus
extern "C" {
#endif
#undef maxit_gui_GUI_FOCUS_TRAVERSABLE_UNKNOWN
#define maxit_gui_GUI_FOCUS_TRAVERSABLE_UNKNOWN 0L
#undef maxit_gui_GUI_FOCUS_TRAVERSABLE_DEFAULT
#define maxit_gui_GUI_FOCUS_TRAVERSABLE_DEFAULT 1L
#undef maxit_gui_GUI_FOCUS_TRAVERSABLE_SET
#define maxit_gui_GUI_FOCUS_TRAVERSABLE_SET 2L
#undef maxit_gui_GUI_TOP_ALIGNMENT
#define maxit_gui_GUI_TOP_ALIGNMENT 0.0f
#undef maxit_gui_GUI_CENTER_ALIGNMENT
#define maxit_gui_GUI_CENTER_ALIGNMENT 0.5f
#undef maxit_gui_GUI_BOTTOM_ALIGNMENT
#define maxit_gui_GUI_BOTTOM_ALIGNMENT 1.0f
#undef maxit_gui_GUI_LEFT_ALIGNMENT
#define maxit_gui_GUI_LEFT_ALIGNMENT 0.0f
#undef maxit_gui_GUI_RIGHT_ALIGNMENT
#define maxit_gui_GUI_RIGHT_ALIGNMENT 1.0f
#undef maxit_gui_GUI_serialVersionUID
#define maxit_gui_GUI_serialVersionUID -7644114512714619750i64
#undef maxit_gui_GUI_serialVersionUID
#define maxit_gui_GUI_serialVersionUID 4613797578919906343i64
#undef maxit_gui_GUI_INCLUDE_SELF
#define maxit_gui_GUI_INCLUDE_SELF 1L
#undef maxit_gui_GUI_SEARCH_HEAVYWEIGHTS
#define maxit_gui_GUI_SEARCH_HEAVYWEIGHTS 1L
#undef maxit_gui_GUI_OPENED
#define maxit_gui_GUI_OPENED 1L
#undef maxit_gui_GUI_serialVersionUID
#define maxit_gui_GUI_serialVersionUID 4497834738069338734i64
#undef maxit_gui_GUI_DEFAULT_CURSOR
#define maxit_gui_GUI_DEFAULT_CURSOR 0L
#undef maxit_gui_GUI_CROSSHAIR_CURSOR
#define maxit_gui_GUI_CROSSHAIR_CURSOR 1L
#undef maxit_gui_GUI_TEXT_CURSOR
#define maxit_gui_GUI_TEXT_CURSOR 2L
#undef maxit_gui_GUI_WAIT_CURSOR
#define maxit_gui_GUI_WAIT_CURSOR 3L
#undef maxit_gui_GUI_SW_RESIZE_CURSOR
#define maxit_gui_GUI_SW_RESIZE_CURSOR 4L
#undef maxit_gui_GUI_SE_RESIZE_CURSOR
#define maxit_gui_GUI_SE_RESIZE_CURSOR 5L
#undef maxit_gui_GUI_NW_RESIZE_CURSOR
#define maxit_gui_GUI_NW_RESIZE_CURSOR 6L
#undef maxit_gui_GUI_NE_RESIZE_CURSOR
#define maxit_gui_GUI_NE_RESIZE_CURSOR 7L
#undef maxit_gui_GUI_N_RESIZE_CURSOR
#define maxit_gui_GUI_N_RESIZE_CURSOR 8L
#undef maxit_gui_GUI_S_RESIZE_CURSOR
#define maxit_gui_GUI_S_RESIZE_CURSOR 9L
#undef maxit_gui_GUI_W_RESIZE_CURSOR
#define maxit_gui_GUI_W_RESIZE_CURSOR 10L
#undef maxit_gui_GUI_E_RESIZE_CURSOR
#define maxit_gui_GUI_E_RESIZE_CURSOR 11L
#undef maxit_gui_GUI_HAND_CURSOR
#define maxit_gui_GUI_HAND_CURSOR 12L
#undef maxit_gui_GUI_MOVE_CURSOR
#define maxit_gui_GUI_MOVE_CURSOR 13L
#undef maxit_gui_GUI_NORMAL
#define maxit_gui_GUI_NORMAL 0L
#undef maxit_gui_GUI_ICONIFIED
#define maxit_gui_GUI_ICONIFIED 1L
#undef maxit_gui_GUI_MAXIMIZED_HORIZ
#define maxit_gui_GUI_MAXIMIZED_HORIZ 2L
#undef maxit_gui_GUI_MAXIMIZED_VERT
#define maxit_gui_GUI_MAXIMIZED_VERT 4L
#undef maxit_gui_GUI_MAXIMIZED_BOTH
#define maxit_gui_GUI_MAXIMIZED_BOTH 6L
#undef maxit_gui_GUI_serialVersionUID
#define maxit_gui_GUI_serialVersionUID 2673458971256075116i64
#undef maxit_gui_GUI_serialVersionUID
#define maxit_gui_GUI_serialVersionUID 1i64
/*
 * Class:     maxit_gui_GUI
 * Method:    getOSScaling
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_maxit_gui_GUI_getOSScaling
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
